version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db/testdb"
      SPRING_DATASOURCE_USERNAME: "test"
      SPRING_DATASOURCE_PASSWORD: "test"
      SPRING_REDIS_HOST: "cache"
      SPRING_REDIS_PORT: "6379"
    depends_on:
      - postgres
      - cache